
# docker-compose.yml


# Usage: docker-compose up -d

services:
  web:
    # depends_on:
      # - db  # Make sure the db service is working first
    restart: on-failure:4  # If the container crashes, try restarting it 4 times
    build:
        dockerfile: dockerfile  # Build the image from the file "Dockerfile"
        tags:  # How should we name the images?
          - timlun/monsterspace:latest
    image: timlun/monsterspace
    ports:
      - 5000:80  # Which ports should we expose?
    environment:
      FLASK_DEBUG: true  # Tell Flask to run in debug mode

# Ett misslyckat försök att skapa en databas som sparas vid varje server restart.
#  db:
#    image: SQLite:latest
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: 'you-will-never-guess'
#    ports:
#      - 3306:3306
#    volumes:
#      - "./.database:/app/app.db"   # lokala mappen : mappen i containern
